### ISSUE TITLE
What happened to previous genshin impact repo? 

### ISSUE THREAD

**Issue by WSrujan** [HANDZCZ/genshin-stats#1]
Is this repo better?

**Comment by HANDZCZ** [comment]
The previous repo got disabled by GitHub.
I rewrote it so it won't get disabled again and switched from deprecated [genshinstats](https://github.com/thesadru/genshinstats#this-library-only-receives-bugfixes-please-use-genshinpy-instead) to [genshin.py](https://github.com/thesadru/genshin.py).

One of the pros is that you can use all the web stuff (CSS, JS, ...), so it looks way nicer than before.
Other is that you can easily integrate it inside your website.
But the biggest one is that this repo holds only the code (not the actual data/website), so it's much easier to navigate in it and to update the app (you just pull all changes from upstream).

Also [this desing](https://github.com/HANDZCZ/genshin-stats/blob/c866717e7cd3ec30ad89fdef5f5c01c06193c84a/template.mako) isn't final since it doesn't use diary at all and a lot of images are missing.

**Comment by WSrujan** [comment]
I have to have heroku right? 
For this to work

**Comment by HANDZCZ** [comment]
Yes, you need to have or create a Heroku account.
